### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by chrismp** [MuckRock/Klaxon#12]
Hey there, it seems all my Klaxon instances are failing. Here's a link to the error log for one job: https://github.com/MuckRock/Klaxon/actions/runs/11289233521/job/31398662247

Full error message

```
Run PAYLOAD=$(jq -r ".client_payload" $GITHUB_EVENT_PATH)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 873, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: /wayback/available?url=https://reactwarn.floridajobs.org/WarnList/Records?year=2024 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/Klaxon/Klaxon/main.py", line 285, in <module>
    Klaxon().main()
  File "/home/runner/work/Klaxon/Klaxon/main.py", line 280, in main
    self.monitor_with_selector(site, selector)
  File "/home/runner/work/Klaxon/Klaxon/main.py", line [18](https://github.com/MuckRock/Klaxon/actions/runs/11289233521/job/31398662247#step:9:19)1, in monitor_with_selector
    self.check_first_seen(site)
  File "/home/runner/work/Klaxon/Klaxon/main.py", line 52, in check_first_seen
    response = requests_retry_session(retries=10).get(archive_test, headers=headers)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: /wayback/available?url=https://reactwarn.floridajobs.org/WarnList/Records?year=[20](https://github.com/MuckRock/Klaxon/actions/runs/11289233521/job/31398662247#step:9:21)24 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
Error: Process completed with exit code 1.
```

**Comment by duckduckgrayduck** [comment]
@chrismp This is because Klaxon relies on the Internet Archive's Wayback Machine as its backend. At the moment, the Wayback machine is read only. When its services are restored fully, Klaxon runs will be re-enabled. I've added a separate issue for this. It's unfortunate, but at the moment Klaxon is down for the time being.
